title: "WreckLab Wiki"
tagline: A web interface for Klipper
description: Documentation for the Wrecklab products
logo: "/assets/img/logo.png"
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
color_scheme: "wrecklab"
search_enabled: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: assets/img/rtfm.png
